#!/bin/bash
pyscript = "import os,subprocess, distro
try:
    import pymusicdl.musicDL
except ImportError:
    print('pymusicdl not found. installing pymusicdl.')
    subprocess.call(['python3', '-m', 'pip', 'install', 'pymusicdl'])
    
os.chdir('~/.local/bin/')
ff = False
try:
    print('Searching for ffmpeg')
    subprocess.check_output(['where', 'ffmpeg'])
    print('ffmpeg found.')
except:
    print('ffmpeg not found.')
    ff=True
if ff:
    if 'Ubuntu' in distro.linux_distribution()[0]:
        print('Downloading ffmpeg')
        subprocess.call(['sudo', 'apt', 'install', 'ffmpeg'])
    else:
        print(f'Download ffmpeg for {distro.linux_distribution()[0]} {distro.linux_distribution()[1]}')
    
if 'musicdl' not in os.listdir():
    mdl = open(r'musicdl','w+')
    mdl.write('#!/bin/bash\npyscript='from pymusicdl.musicDL import main\nmain()'\n\npython3 -c '$pyscript'')
    mdl.close()
    print('Type 'musicdl' in terminal to download music :)')
input('press any key to exit')
"

python3 -c "$pyscript"